import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faBars, faClose } from "@fortawesome/free-solid-svg-icons";

// import static images
import IllustrationWorking from "../public/assets/images/illustration-working.svg";
import BrandRecognitionIcon from "../public/assets/images/icon-brand-recognition.svg";
import DetailedRecordsIcon from "../public/assets/images/icon-detailed-records.svg";
import FullyCustomizableIcon from "../public/assets/images/icon-fully-customizable.svg";
import TwitterIcon from "../public/assets/images/icon-twitter.svg";
import FacebookIcon from "../public/assets/images/icon-facebook.svg";
import PinterestIcon from "../public/assets/images/icon-pinterest.svg";
import InstagramIcon from "../public/assets/images/icon-instagram.svg";

export default function Home() {
  const [input, setInput] = useState("");
  const [link, setLink] = useState("");
  const [shortLink, setShortLink] = useState("Not available");
  const [warning, setWarning] = useState(false);
  const [borderStyle, setBorderStyle] = useState("border-none");
  const [isCopied, setIsCopied] = useState(false);
  const [showShortLink, setShowShortLink] = useState(false);
  const [showMenu, setShowMenu] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (input === "") {
      setWarning(true);
      setBorderStyle("border-4 border-red-500 placeholder-red-400");
      setShowShortLink(false);
      setLink("");
      setShortLink("");
    } else {
      await fetch(`https://api.shrtco.de/v2/shorten?url=${input}`)
        .then((res) => res.json())
        .then((data) => {
          if (data.ok) {
            setShortLink(data.result.full_short_link);
          } else {
            setShortLink("Not available");
          }
        })
        .catch((e) => console.log(e));
      setWarning(false);
      setBorderStyle("border-none");
      setShowShortLink(true);
      setLink(input);
      setIsCopied(false);
    }
  };

  const copyToClipboard = () => {
    if (shortLink !== "Not available") {
      navigator.clipboard.writeText(shortLink);
      setIsCopied(!isCopied);
    }
  };

  return (
    <div>
      <Head>
        <title>Shortly</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="font-body overflow-hidden">
        <header>
          <div className="bg-white p-5">
            <nav className="container mx-auto flex justify-between align-middle">
              <div className="text-4xl font-bold text-primary-dark">
                Shortly
              </div>
              <FontAwesomeIcon
                icon={faBars}
                className="w-6 text-neutral-grayishviolet lg:hidden"
                onClick={() => setShowMenu(true)}
              />
              <div className="hidden flex-1 lg:flex justify-between items-center ml-5">
                <div className="flex">
                  <a className="cursor-pointer text-sm no-underline text-neutral-grayishviolet font-medium mx-5 hover:text-primary-dark">
                    Featured
                  </a>
                  <a className="cursor-pointer text-sm no-underline text-neutral-grayishviolet font-medium mx-5 hover:text-primary-dark">
                    Pricing
                  </a>
                  <a className="cursor-pointer text-sm no-underline text-neutral-grayishviolet font-medium mx-5 hover:text-primary-dark">
                    Resources
                  </a>
                </div>
                <div className="flex items-center">
                  <a className="cursor-pointer text-sm no-underline text-neutral-grayishviolet font-medium mx-5 hover:text-primary-dark">
                    Login
                  </a>
                  <button className="text-sm mx-5 bg-primary text-white hover:bg-hoverprimary px-5 py-2 rounded-full">
                    Pricing
                  </button>
                </div>
              </div>
            </nav>
          </div>
        </header>

        <main>
          {/* mobile menu */}
          <div
            className={
              showMenu
                ? "flex flex-col items-center fixed top-0 left-0 pt-10 bg-white w-full h-full z-20 lg:hidden"
                : "flex flex-col items-center fixed top-0 -left-full pt-10 bg-white w-full h-full z-20 lg:hidden"
            }
          >
            <FontAwesomeIcon
              icon={faClose}
              className="w-6 text-neutral-grayishviolet"
              onClick={() => setShowMenu(false)}
            />
            <a
              href="#"
              onClick={() => setShowMenu(false)}
              className="cursor-pointer text-xl no-underline text-primary-dark font-medium my-2"
            >
              Featured
            </a>
            <a
              href="#"
              onClick={() => setShowMenu(false)}
              className="cursor-pointer text-xl no-underline text-primary-dark font-medium my-2"
            >
              Pricing
            </a>
            <a
              href="#"
              onClick={() => setShowMenu(false)}
              className="cursor-pointer text-xl no-underline text-primary-dark font-medium my-2"
            >
              Resources
            </a>
            <a
              href="#"
              onClick={() => setShowMenu(false)}
              className="cursor-pointer text-xl no-underline text-primary-dark font-medium my-2"
            >
              Login
            </a>
            <button
              className="text-lg my-2 bg-primary text-white hover:bg-hoverprimary px-5 py-2 rounded-full"
              onClick={() => setShowMenu(false)}
            >
              Pricing
            </button>
          </div>
          {/* end of mobile menu */}

          <div className="bg-white px-5 py-10">
            <div className="container mx-auto relative flex flex-col-reverse lg:flex-row lg:mb-20">
              <div className="w-full flex-1 flex flex-col items-center lg:items-start">
                <p
                  className="text-4xl lg:text-5xl text-center font-bold lg:text-left text-primary-dark mt-5"
                  style={{ lineHeight: 1.2 }}
                >
                  More than just shorter links
                </p>
                <p className="text-center lg:text-left text-xl font-medium text-neutral-grayishviolet mt-3">
                  Build your brand's recognition and get detailed insights on
                  how your links are performing.
                </p>
                <button className="border-none bg-primary text-white p-2 px-5 w-max rounded-full mt-5 text-lg mb-20 hover:bg-hoverprimary">
                  Get Started
                </button>
              </div>
              <div className="flex-1 block mb-10 lg:my-0">
                <Image src={IllustrationWorking} alt="Ilustration working" />
              </div>
            </div>
          </div>

          <div className="bg-gray-100 px-5 py-52">
            <div className="container mx-auto relative flex flex-col">
              <div className="absolute w-full left-0 -top-64 transform -translate-y-4">
                <div className="bg-darkblue rounded-lg">
                  <form onSubmit={(e) => handleSubmit(e)}>
                    <div className="w-full p-10 bg-shorten-mobile lg:bg-shorten-desktop bg-no-repeat bg-right-top rounded-lg relative flex flex-col lg:flex-row">
                      <input
                        className={
                          "inline p-2 text-primary-dark rounded-lg text-lg flex-1 " +
                          borderStyle
                        }
                        placeholder="Shorten a link here..."
                        onChange={(e) => setInput(e.target.value)}
                      ></input>
                      {warning && (
                        <p className="text-sm italic text-secondary absolute bottom-24 left-10 lg:bottom-3">
                          Please add a link
                        </p>
                      )}
                      <button
                        type="submit"
                        className={
                          warning
                            ? "border-none bg-primary text-white py-2 px-5 rounded-lg text-lg hover:bg-hoverprimary mt-10 lg:ml-5 lg:mt-0"
                            : "border-none bg-primary text-white py-2 px-5 rounded-lg text-lg hover:bg-hoverprimary mt-3 lg:ml-5 lg:mt-0"
                        }
                      >
                        Shorten It!
                      </button>
                    </div>
                  </form>
                </div>
                {showShortLink && (
                  <div className="relative">
                    <div className="w-full bg-white rounded-lg p-5 flex mt-5 flex-col items-start justify-start lg:flex-row lg:justify-between lg:items-center">
                      <div className="text-lg font-medium text-primary-dark overflow-ellipsis overflow-hidden flex-1 w-full whitespace-nowrap">
                        {link}
                      </div>
                      <div className="flex flex-col w-full lg:w-max mt-8 lg:mt-0 lg:items-center lg:flex-row">
                        <p className="text-lg text-primary-cyan font-medium">
                          {shortLink}
                        </p>
                        <button
                          type="submit"
                          className={
                            isCopied
                              ? "border-none bg-darkblue text-white py-2 px-5 rounded-lg text-md mt-3 lg:mt-0 lg:ml-5"
                              : "border-none bg-primary text-white py-2 px-5 rounded-lg text-md hover:bg-hoverprimary mt-3 lg:mt-0 lg:ml-5"
                          }
                          onClick={() => copyToClipboard()}
                          disabled={isCopied ? true : false}
                        >
                          {isCopied ? "Copied!" : "Copy"}
                        </button>
                      </div>
                    </div>
                    <div className="border-b-2 w-full absolute top-16 lg:hidden"></div>
                  </div>
                )}
              </div>

              <p className="text-3xl font-bold text-primary-dark text-center">
                Advanced Statistic
              </p>
              <p className="text-center text-lg lg:w-1/3 font-medium text-neutral-grayishviolet mt-5 mx-auto">
                Track how your links are performing across the web with our
                advanced statistic dashboard.
              </p>
              <div className="flex relative z-10 flex-col lg:flex-row">
                <div className="w-full bg-white rounded-lg px-5 pb-10 relative mt-20">
                  <div className="bg-darkblue rounded-full flex justify-center items-center p-5 w-max relative mx-auto -top-11 lg:m-0 lg:mx-0">
                    <Image src={BrandRecognitionIcon} alt="brand recognition" />
                  </div>
                  <p className="text-2xl font-bold text-primary-dark text-center lg:text-left">
                    Brand Recognition
                  </p>
                  <p className="text-neutral-grayishviolet text-center mt-5 lg:text-left">
                    Boost your brand recognition with each click. Generic links
                    don't mean a thing. Branded links help instil confidence in
                    your content.
                  </p>
                </div>
                <div className="w-full bg-white rounded-lg px-5 pb-10 relative mt-20 lg:mx-10 lg:transform lg:translate-y-10">
                  <div className="bg-darkblue rounded-full flex justify-center items-center p-5 w-max relative mx-auto -top-11 lg:m-0 lg:mx-0">
                    <Image src={DetailedRecordsIcon} alt="detailed records" />
                  </div>
                  <p className="text-2xl font-bold text-primary-dark text-center lg:text-left">
                    Detailed Records
                  </p>
                  <p className="text-neutral-grayishviolet text-center mt-5 lg:text-left">
                    Gain insights into who is clicking your links. Knowing when
                    and where people engage with your content helps inform
                    better decisions.
                  </p>
                </div>
                <div className="w-full bg-white rounded-lg px-5 pb-10 relative mt-20 lg:transform lg:translate-y-20">
                  <div className="bg-darkblue rounded-full flex justify-center items-center p-5 w-max relative mx-auto -top-11 lg:m-0 lg:mx-0">
                    <Image
                      src={FullyCustomizableIcon}
                      alt="fully customizable"
                    />
                  </div>
                  <p className="text-2xl font-bold text-primary-dark text-center lg:text-left">
                    Fully Customizable
                  </p>
                  <p className="text-neutral-grayishviolet text-center mt-5 lg:text-left">
                    Improve brand awareness and content discoverablitiy though
                    customizable links, supercharging audience engagement
                  </p>
                </div>
              </div>
              <div className="h-2/3 w-2 lg:h-2 lg:w-2/3 bg-primary absolute bottom-28 z-0 left-1/2 transform -translate-x-1/2"></div>
            </div>
          </div>

          <div className="bg-darkblue">
            <div className="bg-boost-mobile lg:bg-boost-desktop bg-no-repeat bg-right py-20 flex flex-col">
              <p className="text-2xl font-bold text-white text-center">
                Boost your links today
              </p>
              <button className="border-none bg-primary text-white p-2 px-5 rounded-full mt-3 mx-auto hover:bg-hoverprimary">
                Get Started
              </button>
            </div>
          </div>

          <div className="bg-darkviolet">
            <div className="container mx-auto flex flex-col px-5 py-10 lg:flex-row">
              <p className="text-white text-center lg:text-left text-3xl font-bold lg:flex-2">
                Shortly
              </p>

              <div className="mt-7 lg:mt-0 lg:flex-1">
                <p className="text-white text-center lg:text-left text-md font-medium">
                  Features
                </p>
                <a
                  href="#"
                  className="mt-5 block text-center lg:text-left text-neutral-grayishviolet text-md hover:text-primary-cyan"
                >
                  Link Shortening
                </a>
                <a
                  href="#"
                  className="block mt-1 text-center lg:text-left text-neutral-grayishviolet text-md hover:text-primary-cyan"
                >
                  Branded Links
                </a>
                <a
                  href="#"
                  className="block mt-1 text-center lg:text-left text-neutral-grayishviolet text-md hover:text-primary-cyan"
                >
                  Analytics
                </a>
              </div>

              <div className="mt-7 lg:mt-0 lg:flex-1">
                <p className="text-white text-center lg:text-left text-md font-medium">
                  Resources
                </p>
                <a
                  href="#"
                  className="block mt-5 text-center lg:text-left text-neutral-grayishviolet text-md hover:text-primary-cyan"
                >
                  Blog
                </a>
                <a
                  href="#"
                  className="block mt-1 text-center lg:text-left text-neutral-grayishviolet text-md hover:text-primary-cyan"
                >
                  Developers
                </a>
                <a
                  href="#"
                  className="block mt-1 text-center lg:text-left text-neutral-grayishviolet text-md hover:text-primary-cyan"
                >
                  Support
                </a>
              </div>

              <div className="mt-7 lg:mt-0 lg:flex-1">
                <p className="text-white text-center lg:text-left text-md font-medium">
                  Company
                </p>
                <a
                  href="#"
                  className="block mt-5 text-center lg:text-left text-neutral-grayishviolet text-md hover:text-primary-cyan"
                >
                  About
                </a>
                <a
                  href="#"
                  className="block mt-1 text-center lg:text-left text-neutral-grayishviolet text-md hover:text-primary-cyan"
                >
                  Out Team
                </a>
                <a
                  href="#"
                  className="block mt-1 text-center lg:text-left text-neutral-grayishviolet text-md hover:text-primary-cyan"
                >
                  Careers
                </a>
                <a
                  href="#"
                  className="block mt-1 text-center lg:text-left text-neutral-grayishviolet text-md hover:text-primary-cyan"
                >
                  Contact
                </a>
              </div>

              <div className="flex justify-center mt-10 lg:mt-0 lg:flex-1">
                <a href="#" className="w-max mx-3">
                  <Image
                    src={FacebookIcon}
                    alt="facebook"
                    width="23"
                    height="23"
                    layout="fixed"
                  ></Image>
                </a>
                <div className="block w-max mx-3">
                  <Image
                    src={TwitterIcon}
                    alt="twitter"
                    width="25"
                    height="23"
                    layout="fixed"
                  ></Image>
                </div>
                <a href="#" className="w-max mx-3">
                  <Image
                    src={InstagramIcon}
                    alt="pinterest"
                    width="23"
                    height="23"
                    layout="fixed"
                  ></Image>
                </a>
                <a href="#" className="w-max mx-3">
                  <Image
                    src={PinterestIcon}
                    alt="instagram"
                    width="23"
                    height="23"
                    layout="fixed"
                  ></Image>
                </a>
              </div>
            </div>
          </div>
        </main>
      </div>
    </div>
  );
}
